# Unconditional sampling
defaults:
  - _inference
  - _self_

data:
  task: hallucination

  dataset: fold # go

  sampler:
    # Setting for 40GB GPUs
    max_batch_size: 64
    max_num_res_squared: 400_000


inference:

  predict_dir: ./inference_outputs/
  inference_subdir: run_${now:%Y-%m-%d}_${now:%H-%M-%S}
  task: unconditional
  seed: 123
  use_gpu: True
  num_gpus: 1

  unconditional_ckpt_path: weights/pdb/published.ckpt
  output_dir: ./extract_output/fold # go
